name: Go release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Tag version
        uses: kyoh86/git-vertag-action@v1
        with:
          method: patch # "major", "minor", "patch" or "get"
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_COM }}
